fruits=['orange','melon','banana']
print(fruits)
print(len(fruits))
fruits.append('cherry')
print(fruits)
fruits.insert(2,'strawberry')
print(fruits)
fruits.remove('cherry')
print(fruits)
fruits.pop()
print(fruits)
fruits.pop(2)
print(fruits)
fruits2=['banana','pinapple']
fruits3=fruits.copy()+fruits2
print(fruits3)
fruits3.clear()
print(fruits3)