import MyModule
y=MyModule.func(3,2)
print('3 * 2 = ')
print(y)
f=MyModule.func2(3,2)
print('3 + 2 = ')
print(f)
b=MyModule.func3(3,2)
print('3 - 2 = ')
print(b)
d=MyModule.func4(3,2)
print('3 / 2 = ')
print(d)
import datetime
t=datetime.datetime.now()
print(t.year)
print(t.day)
print(t.month)
print(t.date())